const pdfParse = require('pdf-parse');
const CoverLetter = require('../models/coverLetterSchema.js');
const {GoogleGenAI}= require('@google/genai');
const API_KEY = process.env.GOOGLE_GEN_AI_API_KEY;
const generateCoverLetter = async (req, res) => {
    console.log(req.body);
    try{
        const { jobDescription,
            skillsFocus,
            recruiterName,
            recruiterDesignation,
            companyName } = req.body;
        if (!req.file) {
            return res.status(400).json({ error: 'Resume file is required' });
        }
        const resumeData = await pdfParse(req.file.buffer);
        const resumeText = resumeData.text;
        const prompt =`You are an expert HR writer and resume analyst with 20+ years of experience writing high-impact cover letters.

Your task is to generate a professional, concise, and job-targeted cover letter using the data below.

---------------------
RESUME CONTENT (Use ONLY skills and experience found here. Do NOT add anything new):
${resumeText}
---------------------

---------------------
JOB DESCRIPTION:
${jobDescription}
---------------------

---------------------
SKILLS TO HIGHLIGHT (Use these ONLY if they exist in the resume):
${skillsFocus}
---------------------

---------------------
RECRUITER DETAILS:
Name: ${recruiterName}
Designation: ${recruiterDesignation}
Company: ${companyName}
---------------------

---------------------
STRICT RULES:
1. You MUST use only the candidate's actual skills, achievements, tools, projects, and experience that appear in the resume text above.
   - Do NOT invent skills.
   - Do NOT add technologies not in the resume.
   - Do NOT fabricate job titles or achievements.
   - If the resume lacks a skill from “Skills to Highlight,” ignore it.

2. Read the job description and EXTRACT the job title automatically.
3. Tailor the letter to match:
   - the job responsibilities
   - the required skills
   - the real experience from the resume
   - the highlighted skills (only if present in the resume)

4. Tone:
   - confident
   - professional
   - sincere
   - aligned with the company's needs

5. Structure:
   - Strong opening line
   - 2 to 3 focused paragraphs connecting resume → job description
   - Highlight achievements and skills that match the job
   - Include recruiter details
   - Courteous closing paragraph

6. Length:
   - 150 to 250 words
   - NO bullet points

7. Format:
   - Start with “Dear {recruiterName},” or “Dear Hiring Manager,” if empty
   - Do NOT mention job title extraction
   - Do NOT say this was generated by AI

8. FINAL OUTPUT:
   - Return ONLY the final cover letter text.
   - NO explanations, NO notes.

`
    const ai = new GoogleGenAI({ apiKey: API_KEY });
    const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: prompt,
    })
    const generatedLetter = response.text.trim();
        const saved=await CoverLetter.create({
            jobDescription,
            skillsFocus,
            resumeText,
            recruiterName,
            recruiterDesignation,
            companyName,
            generatedLetter
        });
        res.status(200).json({
            success:true,
            coverLetter:generatedLetter,
            id:saved._id
        });
    }
    catch(error){
        console.error("Error generating cover letter:",error);
        res.status(500).json({error:"Failed to generate cover letter"});
    }
}
module.exports={generateCoverLetter};